#############################################################################
# Makefile for building: bin/Translator.app/Contents/MacOS/Translator
# Generated by qmake (2.01a) (Qt 4.6.2) on: Tue Jun 22 13:40:54 2010
# Project:  Translator.pro
# Template: app
# Command: /usr/bin/qmake -spec /usr/local/Qt4.6/mkspecs/macx-g++ -macx -o Makefile Translator.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_SCRIPT_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -gdwarf-2 -arch i386 -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -g -gdwarf-2 -arch i386 -Wall -W $(DEFINES)
INCPATH       = -I/usr/local/Qt4.6/mkspecs/macx-g++ -I. -I/Library/Frameworks/QtCore.framework/Versions/4/Headers -I/usr/include/QtCore -I/Library/Frameworks/QtNetwork.framework/Versions/4/Headers -I/usr/include/QtNetwork -I/Library/Frameworks/QtGui.framework/Versions/4/Headers -I/usr/include/QtGui -I/Library/Frameworks/QtScript.framework/Versions/4/Headers -I/usr/include/QtScript -I/usr/include -Isrc/qtsingleapplication -Itemp -Itemp -F/Library/Frameworks
LINK          = g++
LFLAGS        = -headerpad_max_install_names -arch i386
LIBS          = $(SUBLIBS) -F/Library/Frameworks -L/Library/Frameworks -framework QtScript -framework QtGui -framework QtNetwork -framework QtCore 
AR            = ar cq
RANLIB        = ranlib -s
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
export MACOSX_DEPLOYMENT_TARGET = 10.4

####### Output directory

OBJECTS_DIR   = temp/

####### Files

SOURCES       = src/qtsingleapplication/qtsingleapplication.cpp \
		src/qtsingleapplication/qtlocalpeer.cpp \
		src/main.cpp \
		src/wnd.cpp \
		src/aboutappwnd.cpp \
		src/googleproto.cpp \
		src/settingswnd.cpp \
		src/jsonstreamreader.cpp temp/moc_qtsingleapplication.cpp \
		temp/moc_qtlocalpeer.cpp \
		temp/moc_wnd.cpp \
		temp/moc_aboutappwnd.cpp \
		temp/moc_googleproto.cpp \
		temp/moc_settingswnd.cpp \
		temp/qrc_resources.cpp
OBJECTS       = temp/qtsingleapplication.o \
		temp/qtlocalpeer.o \
		temp/main.o \
		temp/wnd.o \
		temp/aboutappwnd.o \
		temp/googleproto.o \
		temp/settingswnd.o \
		temp/jsonstreamreader.o \
		temp/moc_qtsingleapplication.o \
		temp/moc_qtlocalpeer.o \
		temp/moc_wnd.o \
		temp/moc_aboutappwnd.o \
		temp/moc_googleproto.o \
		temp/moc_settingswnd.o \
		temp/qrc_resources.o
DIST          = /usr/local/Qt4.6/mkspecs/common/unix.conf \
		/usr/local/Qt4.6/mkspecs/common/mac.conf \
		/usr/local/Qt4.6/mkspecs/common/mac-g++.conf \
		/usr/local/Qt4.6/mkspecs/qconfig.pri \
		/usr/local/Qt4.6/mkspecs/features/qt_functions.prf \
		/usr/local/Qt4.6/mkspecs/features/qt_config.prf \
		/usr/local/Qt4.6/mkspecs/features/exclusive_builds.prf \
		/usr/local/Qt4.6/mkspecs/features/default_pre.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/default_pre.prf \
		src/qtsingleapplication/qtsingleapplication.pri \
		/usr/local/Qt4.6/mkspecs/features/mac/dwarf2.prf \
		/usr/local/Qt4.6/mkspecs/features/debug.prf \
		/usr/local/Qt4.6/mkspecs/features/default_post.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/default_post.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/x86.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/objective_c.prf \
		/usr/local/Qt4.6/mkspecs/features/warn_on.prf \
		/usr/local/Qt4.6/mkspecs/features/qt.prf \
		/usr/local/Qt4.6/mkspecs/features/unix/thread.prf \
		/usr/local/Qt4.6/mkspecs/features/moc.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/rez.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/sdk.prf \
		/usr/local/Qt4.6/mkspecs/features/resources.prf \
		/usr/local/Qt4.6/mkspecs/features/uic.prf \
		/usr/local/Qt4.6/mkspecs/features/yacc.prf \
		/usr/local/Qt4.6/mkspecs/features/lex.prf \
		Translator.pro
QMAKE_TARGET  = Translator
DESTDIR       = bin/
TARGET        = bin/Translator.app/Contents/MacOS/Translator

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-g \
		-gdwarf-2 \
		-arch \
		i386 \
		-Wall \
		-W


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile bin/Translator.app/Contents/PkgInfo bin/Translator.app/Contents/Resources/empty.lproj $(TARGET)

$(TARGET): temp/ui_wnd.h temp/ui_settingswnd.h $(OBJECTS)  
	@$(CHK_DIR_EXISTS) bin/Translator.app/Contents/MacOS/ || $(MKDIR) bin/Translator.app/Contents/MacOS/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Translator.pro  /usr/local/Qt4.6/mkspecs/macx-g++/qmake.conf /usr/local/Qt4.6/mkspecs/common/unix.conf \
		/usr/local/Qt4.6/mkspecs/common/mac.conf \
		/usr/local/Qt4.6/mkspecs/common/mac-g++.conf \
		/usr/local/Qt4.6/mkspecs/qconfig.pri \
		/usr/local/Qt4.6/mkspecs/features/qt_functions.prf \
		/usr/local/Qt4.6/mkspecs/features/qt_config.prf \
		/usr/local/Qt4.6/mkspecs/features/exclusive_builds.prf \
		/usr/local/Qt4.6/mkspecs/features/default_pre.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/default_pre.prf \
		src/qtsingleapplication/qtsingleapplication.pri \
		/usr/local/Qt4.6/mkspecs/features/mac/dwarf2.prf \
		/usr/local/Qt4.6/mkspecs/features/debug.prf \
		/usr/local/Qt4.6/mkspecs/features/default_post.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/default_post.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/x86.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/objective_c.prf \
		/usr/local/Qt4.6/mkspecs/features/warn_on.prf \
		/usr/local/Qt4.6/mkspecs/features/qt.prf \
		/usr/local/Qt4.6/mkspecs/features/unix/thread.prf \
		/usr/local/Qt4.6/mkspecs/features/moc.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/rez.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/sdk.prf \
		/usr/local/Qt4.6/mkspecs/features/resources.prf \
		/usr/local/Qt4.6/mkspecs/features/uic.prf \
		/usr/local/Qt4.6/mkspecs/features/yacc.prf \
		/usr/local/Qt4.6/mkspecs/features/lex.prf \
		/Library/Frameworks/QtScript.framework/QtScript.prl \
		/Library/Frameworks/QtCore.framework/QtCore.prl \
		/Library/Frameworks/QtGui.framework/QtGui.prl \
		/Library/Frameworks/QtNetwork.framework/QtNetwork.prl
	$(QMAKE) -spec /usr/local/Qt4.6/mkspecs/macx-g++ -macx -o Makefile Translator.pro
/usr/local/Qt4.6/mkspecs/common/unix.conf:
/usr/local/Qt4.6/mkspecs/common/mac.conf:
/usr/local/Qt4.6/mkspecs/common/mac-g++.conf:
/usr/local/Qt4.6/mkspecs/qconfig.pri:
/usr/local/Qt4.6/mkspecs/features/qt_functions.prf:
/usr/local/Qt4.6/mkspecs/features/qt_config.prf:
/usr/local/Qt4.6/mkspecs/features/exclusive_builds.prf:
/usr/local/Qt4.6/mkspecs/features/default_pre.prf:
/usr/local/Qt4.6/mkspecs/features/mac/default_pre.prf:
src/qtsingleapplication/qtsingleapplication.pri:
/usr/local/Qt4.6/mkspecs/features/mac/dwarf2.prf:
/usr/local/Qt4.6/mkspecs/features/debug.prf:
/usr/local/Qt4.6/mkspecs/features/default_post.prf:
/usr/local/Qt4.6/mkspecs/features/mac/default_post.prf:
/usr/local/Qt4.6/mkspecs/features/mac/x86.prf:
/usr/local/Qt4.6/mkspecs/features/mac/objective_c.prf:
/usr/local/Qt4.6/mkspecs/features/warn_on.prf:
/usr/local/Qt4.6/mkspecs/features/qt.prf:
/usr/local/Qt4.6/mkspecs/features/unix/thread.prf:
/usr/local/Qt4.6/mkspecs/features/moc.prf:
/usr/local/Qt4.6/mkspecs/features/mac/rez.prf:
/usr/local/Qt4.6/mkspecs/features/mac/sdk.prf:
/usr/local/Qt4.6/mkspecs/features/resources.prf:
/usr/local/Qt4.6/mkspecs/features/uic.prf:
/usr/local/Qt4.6/mkspecs/features/yacc.prf:
/usr/local/Qt4.6/mkspecs/features/lex.prf:
/Library/Frameworks/QtScript.framework/QtScript.prl:
/Library/Frameworks/QtCore.framework/QtCore.prl:
/Library/Frameworks/QtGui.framework/QtGui.prl:
/Library/Frameworks/QtNetwork.framework/QtNetwork.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/local/Qt4.6/mkspecs/macx-g++ -macx -o Makefile Translator.pro

bin/Translator.app/Contents/PkgInfo: 
	@$(CHK_DIR_EXISTS) bin/Translator.app/Contents || $(MKDIR) bin/Translator.app/Contents 
	@$(DEL_FILE) bin/Translator.app/Contents/PkgInfo
	@echo "APPL????" >bin/Translator.app/Contents/PkgInfo
bin/Translator.app/Contents/Resources/empty.lproj: 
	@$(CHK_DIR_EXISTS) bin/Translator.app/Contents/Resources || $(MKDIR) bin/Translator.app/Contents/Resources 
	@touch bin/Translator.app/Contents/Resources/empty.lproj
	
: 
	@$(DEL_FILE) 
	@sed -e "s,@ICON@,icon.icns,g" -e "s,@EXECUTABLE@,Translator,g" -e "s,@TYPEINFO@,????,g" res/mac/Info.plist >
bin/Translator.app/Contents/Resources/icon.icns: src/res/icon.icns
	@$(CHK_DIR_EXISTS) bin/Translator.app/Contents/Resources/ || $(MKDIR) bin/Translator.app/Contents/Resources/ 
	@$(DEL_FILE) bin/Translator.app/Contents/Resources/icon.icns
	@$(COPY_FILE) src/res/icon.icns bin/Translator.app/Contents/Resources/icon.icns
dist: 
	@$(CHK_DIR_EXISTS) temp/Translator1.0.0 || $(MKDIR) temp/Translator1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) temp/Translator1.0.0/ && $(COPY_FILE) --parents src/qtsingleapplication/qtsingleapplication.h src/qtsingleapplication/qtlocalpeer.h src/wnd.h src/aboutappwnd.h src/googleproto.h src/settingswnd.h src/jsonstreamreader.h temp/Translator1.0.0/ && $(COPY_FILE) --parents src/resources.qrc temp/Translator1.0.0/ && $(COPY_FILE) --parents src/qtsingleapplication/qtsingleapplication.cpp src/qtsingleapplication/qtlocalpeer.cpp src/main.cpp src/wnd.cpp src/aboutappwnd.cpp src/googleproto.cpp src/settingswnd.cpp src/jsonstreamreader.cpp temp/Translator1.0.0/ && $(COPY_FILE) --parents src/wnd.ui src/settingswnd.ui temp/Translator1.0.0/ && (cd `dirname temp/Translator1.0.0` && $(TAR) Translator1.0.0.tar Translator1.0.0 && $(COMPRESS) Translator1.0.0.tar) && $(MOVE) `dirname temp/Translator1.0.0`/Translator1.0.0.tar.gz . && $(DEL_FILE) -r temp/Translator1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) -r bin/Translator.app
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_moc_header_make_all: temp/moc_qtsingleapplication.cpp temp/moc_qtlocalpeer.cpp temp/moc_wnd.cpp temp/moc_aboutappwnd.cpp temp/moc_googleproto.cpp temp/moc_settingswnd.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) temp/moc_qtsingleapplication.cpp temp/moc_qtlocalpeer.cpp temp/moc_wnd.cpp temp/moc_aboutappwnd.cpp temp/moc_googleproto.cpp temp/moc_settingswnd.cpp
temp/moc_qtsingleapplication.cpp: src/qtsingleapplication/qtsingleapplication.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ src/qtsingleapplication/qtsingleapplication.h -o temp/moc_qtsingleapplication.cpp

temp/moc_qtlocalpeer.cpp: src/qtsingleapplication/qtlockedfile.h \
		src/qtsingleapplication/qtlocalpeer.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ src/qtsingleapplication/qtlocalpeer.h -o temp/moc_qtlocalpeer.cpp

temp/moc_wnd.cpp: src/aboutappwnd.h \
		src/settingswnd.h \
		src/googleproto.h \
		src/jsonstreamreader.h \
		src/wnd.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ src/wnd.h -o temp/moc_wnd.cpp

temp/moc_aboutappwnd.cpp: src/aboutappwnd.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ src/aboutappwnd.h -o temp/moc_aboutappwnd.cpp

temp/moc_googleproto.cpp: src/jsonstreamreader.h \
		src/googleproto.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ src/googleproto.h -o temp/moc_googleproto.cpp

temp/moc_settingswnd.cpp: src/settingswnd.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ src/settingswnd.h -o temp/moc_settingswnd.cpp

compiler_rcc_make_all: temp/qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) temp/qrc_resources.cpp
temp/qrc_resources.cpp: src/resources.qrc \
		src/res/swap.png \
		src/res/icon.png \
		src/res/icon-128.png \
		src/res/flags/ko.png \
		src/res/flags/gl.png \
		src/res/flags/auto.png \
		src/res/flags/tl.png \
		src/res/flags/lt.png \
		src/res/flags/sv.png \
		src/res/flags/fi.png \
		src/res/flags/no.png \
		src/res/flags/da.png \
		src/res/flags/el.png \
		src/res/flags/es.png \
		src/res/flags/hr.png \
		src/res/flags/uk.png \
		src/res/flags/bg.png \
		src/res/flags/vi.png \
		src/res/flags/sq.png \
		src/res/flags/iw.png \
		src/res/flags/et.png \
		src/res/flags/lv.png \
		src/res/flags/th.png \
		src/res/flags/zh-CN.png \
		src/res/flags/pl.png \
		src/res/flags/cs.png \
		src/res/flags/sk.png \
		src/res/flags/fr.png \
		src/res/flags/mt.png \
		src/res/flags/en.png \
		src/res/flags/ja.png \
		src/res/flags/sr.png \
		src/res/flags/ar.png \
		src/res/flags/id.png \
		src/res/flags/ru.png \
		src/res/flags/sl.png \
		src/res/flags/pt.png \
		src/res/flags/ro.png \
		src/res/flags/nl.png \
		src/res/flags/zh-TW.png \
		src/res/flags/hu.png \
		src/res/flags/de.png \
		src/res/flags/ca.png \
		src/res/flags/hi.png \
		src/res/flags/tr.png \
		src/res/flags/it.png
	/Developer/Tools/Qt/rcc -name resources src/resources.qrc -o temp/qrc_resources.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_uic_make_all: temp/ui_wnd.h temp/ui_settingswnd.h
compiler_uic_clean:
	-$(DEL_FILE) temp/ui_wnd.h temp/ui_settingswnd.h
temp/ui_wnd.h: src/wnd.ui
	/Developer/Tools/Qt/uic src/wnd.ui -o temp/ui_wnd.h

temp/ui_settingswnd.h: src/settingswnd.ui
	/Developer/Tools/Qt/uic src/settingswnd.ui -o temp/ui_settingswnd.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

temp/qtsingleapplication.o: src/qtsingleapplication/qtsingleapplication.cpp src/qtsingleapplication/qtsingleapplication.h \
		src/qtsingleapplication/qtlocalpeer.h \
		src/qtsingleapplication/qtlockedfile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o temp/qtsingleapplication.o src/qtsingleapplication/qtsingleapplication.cpp

temp/qtlocalpeer.o: src/qtsingleapplication/qtlocalpeer.cpp src/qtsingleapplication/qtlocalpeer.h \
		src/qtsingleapplication/qtlockedfile.h \
		src/qtsingleapplication/qtlockedfile.cpp \
		src/qtsingleapplication/qtlockedfile_win.cpp \
		src/qtsingleapplication/qtlockedfile_unix.cpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o temp/qtlocalpeer.o src/qtsingleapplication/qtlocalpeer.cpp

temp/main.o: src/main.cpp src/qtsingleapplication/QtSingleApplication \
		src/qtsingleapplication/qtsingleapplication.h \
		src/wnd.h \
		src/aboutappwnd.h \
		src/settingswnd.h \
		src/googleproto.h \
		src/jsonstreamreader.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o temp/main.o src/main.cpp

temp/wnd.o: src/wnd.cpp src/wnd.h \
		src/aboutappwnd.h \
		src/settingswnd.h \
		src/googleproto.h \
		src/jsonstreamreader.h \
		temp/ui_wnd.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o temp/wnd.o src/wnd.cpp

temp/aboutappwnd.o: src/aboutappwnd.cpp src/aboutappwnd.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o temp/aboutappwnd.o src/aboutappwnd.cpp

temp/googleproto.o: src/googleproto.cpp src/googleproto.h \
		src/jsonstreamreader.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o temp/googleproto.o src/googleproto.cpp

temp/settingswnd.o: src/settingswnd.cpp src/settingswnd.h \
		temp/ui_settingswnd.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o temp/settingswnd.o src/settingswnd.cpp

temp/jsonstreamreader.o: src/jsonstreamreader.cpp src/jsonstreamreader.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o temp/jsonstreamreader.o src/jsonstreamreader.cpp

temp/moc_qtsingleapplication.o: temp/moc_qtsingleapplication.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o temp/moc_qtsingleapplication.o temp/moc_qtsingleapplication.cpp

temp/moc_qtlocalpeer.o: temp/moc_qtlocalpeer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o temp/moc_qtlocalpeer.o temp/moc_qtlocalpeer.cpp

temp/moc_wnd.o: temp/moc_wnd.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o temp/moc_wnd.o temp/moc_wnd.cpp

temp/moc_aboutappwnd.o: temp/moc_aboutappwnd.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o temp/moc_aboutappwnd.o temp/moc_aboutappwnd.cpp

temp/moc_googleproto.o: temp/moc_googleproto.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o temp/moc_googleproto.o temp/moc_googleproto.cpp

temp/moc_settingswnd.o: temp/moc_settingswnd.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o temp/moc_settingswnd.o temp/moc_settingswnd.cpp

temp/qrc_resources.o: temp/qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o temp/qrc_resources.o temp/qrc_resources.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

